apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-application
  namespace: default
  labels:
    app: webApp
    environment: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/nathekame/k8-argo-cd.git'
    targetRevision: main
    path: helm-chart
    helm:
      valueFiles:
        - Values.yaml
      releaseName: devopstestv1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10 
