{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}-mysql
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql # This label now matches the Deployment's pod labels
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql # The selector now correctly targets the MySQL pods
{{- end }}
